// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDO_e0dLtiyKgKVJuhznhupNNWQaYCaLU',
    appId: '1:443986956737:web:a3f9f8aa0623541251df40',
    messagingSenderId: '443986956737',
    projectId: 'notetakingapp-d8c19',
    authDomain: 'notetakingapp-d8c19.firebaseapp.com',
    storageBucket: 'notetakingapp-d8c19.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY-rBzDlVBaf_0XEdvQlZhLA9Q96V2YiE',
    appId: '1:443986956737:android:b2c03009ed38577e51df40',
    messagingSenderId: '443986956737',
    projectId: 'notetakingapp-d8c19',
    storageBucket: 'notetakingapp-d8c19.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOIZWlNxtpX5kxDF8h8n7DZBN0de16qb4',
    appId: '1:443986956737:ios:7e598c88b698d70851df40',
    messagingSenderId: '443986956737',
    projectId: 'notetakingapp-d8c19',
    storageBucket: 'notetakingapp-d8c19.firebasestorage.app',
    iosBundleId: 'com.example.flutterAudiobook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOIZWlNxtpX5kxDF8h8n7DZBN0de16qb4',
    appId: '1:443986956737:ios:7e598c88b698d70851df40',
    messagingSenderId: '443986956737',
    projectId: 'notetakingapp-d8c19',
    storageBucket: 'notetakingapp-d8c19.firebasestorage.app',
    iosBundleId: 'com.example.flutterAudiobook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDO_e0dLtiyKgKVJuhznhupNNWQaYCaLU',
    appId: '1:443986956737:web:6d1a91f5dd5efccd51df40',
    messagingSenderId: '443986956737',
    projectId: 'notetakingapp-d8c19',
    authDomain: 'notetakingapp-d8c19.firebaseapp.com',
    storageBucket: 'notetakingapp-d8c19.firebasestorage.app',
  );
}
